#!/usr/bin/env python3
"""
attempt_log.py -- the attempt-log deliverable: every attempt, with its score, readable by a human.

    python scripts/attempt_log.py runs/*/*.jsonl          -> ATTEMPTS.md + attempts_all.csv

ATTEMPTS.md: one line per RUN (experiment, level, run): its round-by-round reward trajectory with the
failure bucket of each round, e.g.  0.62 swapped_axes -> 1.00 solved, and the claim + confidence the
agent made at the end. attempts_all.csv: one row per ATTEMPT (every model reply), with reward, bucket,
input/output tokens and the first 200 characters of the checker's feedback -- the full prompt, code
and feedback stay in the jsonl files next to it.
"""

import collections
import csv
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "projects", "02-kernel-agent"))
import verdicts  # noqa: E402

EXP_DESC = {
    "base": "baseline: upstream agent behaviour",
    "skel": "E1 --skeleton",
    "retr": "E2 --retrieve (reverted)",
    "c1": "C1 skeleton + v2 (swapped-axes instruction)",
    "c2": "C2 + v3 (L1 window reduce) + directional",
    "c2L5": "L5 control (upstream traffic hint)",
    "c3L5": "L5 treatment (+v4: hoist lhsT out of n)",
    "c5": "+v5 load-once (L5-7)",
    "c2hi": "L6/L7 control (upstream hints)",
    "c7": "+v7 (never-loaded inputs)",
    "c8a": "L6 + v8 (k-loop outside)",
    "c8b": "L6 + prompt fix (L6 hint = L7's)",
    "c6": "L8 skeleton + v6", "c6ctl": "L8 control", "c8": "L8 + v8",
    "c9": "C9 final-agent candidate", "c9b": "C9 with the L8 prompt fix scoped",
    "c10": "C10 FINAL AGENT (+v9 signature lint)", "c11": "C11 (+v10, L8)",
    "A": "Stage A v1", "A2": "Stage A v2", "A3": "Stage A v3", "A4": "Stage A v4",
    "A5": "Stage A v4-rules", "A6": "Stage A v4-smart",
}


def exp_of(tag):
    t = (tag or "?").split("_L")[0]
    return t.replace("_qwen", "")


def main(paths):
    sys.stdout.reconfigure(encoding="utf-8")
    runs = collections.OrderedDict()
    claims = {}
    rows = []
    seen = set()
    for p in sorted(paths):
        for line in open(p, encoding="utf-8"):
            if not line.strip():
                continue
            r = json.loads(line)
            key = (r.get("tag"), r.get("run", 0), r["level"])
            if "claim" in r:
                claims[key] = r
                continue
            # one row per distinct (run, round, sample): snapshots can contain the same file twice
            uid = key + (r["round"], r.get("sample", 0))
            if uid in seen:
                continue
            seen.add(uid)
            b = r.get("bucket") if r.get("stage") == "A" else verdicts.classify(r.get("feedback", ""))
            runs.setdefault(key, []).append((r["round"], r["reward"], b))
            u = r.get("usage") or {}
            rows.append(dict(stage=r.get("stage", "B"), experiment=exp_of(r.get("tag")), tag=r.get("tag"),
                             run=r.get("run", 0), level=r["level"], round=r["round"],
                             reward=round(r["reward"], 3), bucket=b,
                             prompt_tokens=u.get("prompt_tokens"), completion_tokens=u.get("completion_tokens"),
                             finish=r.get("finish"),
                             feedback=(r.get("feedback") or "")[:200].replace("\n", " ")))
    with open("attempts_all.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)

    out = ["# ATTEMPTS — every attempt, with its score",
           "",
           f"Generated by `scripts/attempt_log.py` from {len(paths)} logs: **{len(runs)} runs, "
           f"{len(rows)} attempts**. One line per run: round-by-round reward with the failure bucket the "
           f"checker assigned, then the agent's own claim. Full prompts, code and feedback: the jsonl files "
           f"under `runs/`. One row per attempt: `attempts_all.csv`. Rewards: 0.1 parses · +0.2 rules "
           f"clean · +0.2 runs · +0.5 × fraction of shapes correct (Stage B); Stage A the same over its "
           f"cases. All **[sim]** (Stage B) / CPU numpy (Stage A).",
           ""]
    by_exp = collections.OrderedDict()
    for key, rs in runs.items():
        by_exp.setdefault(exp_of(key[0]), []).append((key, sorted(rs)))
    for exp, items in by_exp.items():
        out.append(f"## {exp} — {EXP_DESC.get(exp, '')}")
        out.append("")
        out.append("| level | run | trajectory (reward bucket → …) | claim |")
        out.append("|---|---|---|---|")
        for key, rs in sorted(items, key=lambda kv: (kv[0][2], str(kv[0][0]), kv[0][1])):
            traj = " → ".join(f"{rw:.2f} {b}" for _, rw, b in rs)
            c = claims.get(key)
            claim = (f"SOLVED, conf {c['confidence']:.2f}" if c and c.get("claim") == "solved"
                     else "could not verify" if c else "")
            out.append(f"| L{key[2]} | {key[0]} r{key[1]} | {traj} | {claim} |")
        out.append("")
    open("ATTEMPTS.md", "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print(f"ATTEMPTS.md: {len(runs)} runs; attempts_all.csv: {len(rows)} attempts")


if __name__ == "__main__":
    main([q for a in sys.argv[1:] for q in glob.glob(a)])
