"""Heuristics for the kernel-writing agent: an always-on card, keyword retrieval, and error-to-rule lookup.

    from heuristics import heuristics as H
    H.card()                       # tier-0 rules, ~350 tokens, safe to put in every prompt
    H.retrieve("psum accumulate K loop", k=5)
    H.for_error(traceback_text)    # rules whose trigger/check matches the failure, as instructions

Data: rules.json next to this file (generated by merge_heuristics.py). Nothing here calls a model;
the point is to turn a 724-rule database into a few hundred tokens the model can act on, with the
source of each rule attached so a human can audit it.
"""
from __future__ import annotations

import json, math, os, re
from collections import Counter

_HERE = os.path.dirname(os.path.abspath(__file__))
_RULES = None
_IDF = None
_STOP = set("the a an of to in for and or is are be with on at by from that this it as into when then than its use".split())


def _tok(s):
    return [t for t in re.findall(r"[a-z0-9_\.]+", (s or "").lower()) if t not in _STOP and len(t) > 1]


def rules():
    global _RULES, _IDF
    if _RULES is None:
        _RULES = json.load(open(os.path.join(_HERE, "rules.json")))
        df = Counter()
        for r in _RULES:
            r["_tokens"] = Counter(_tok(" ".join([r["id"].replace("-", " "), r["rule"], r.get("trigger") or "",
                                                 r.get("fix") or "", r.get("check_sketch") or "", r["category"]])))
            df.update(r["_tokens"].keys())
        n = len(_RULES)
        _IDF = {t: math.log((n + 1) / (c + 1)) + 1 for t, c in df.items()}
    return _RULES


def retrieve(query, k=5, category=None, detectable=None):
    """Top-k rules by a tf-idf-ish keyword score. Returns the rule dicts (with scores)."""
    q = Counter(_tok(query))
    scored = []
    for r in rules():
        if category and r["category"] != category:
            continue
        if detectable and r["detectable"] != detectable:
            continue
        s = sum(_IDF.get(t, 1.0) * min(cnt, 2) for t, cnt in q.items() if t in r["_tokens"])
        if s > 0:
            scored.append((s, r))
    scored.sort(key=lambda x: -x[0])
    return [dict(r, score=round(s, 2)) for s, r in scored[:k]]


def as_instruction(r):
    """One rule as a 'change exactly this' line (the form that measured best in this repo)."""
    fix = (r.get("fix") or r["rule"]).strip().replace("\n", " ")
    return f"{fix} ({r['id']})"


def card(ids=None, max_rules=20):
    """The always-on card: tier-0 rules as short imperative lines."""
    rs = [r for r in rules() if (r["id"] in ids if ids else r.get("tier") == 0)][:max_rules]
    lines = ["NKI rules that matter most for a memory-bound kernel:"]
    for r in rs:
        lines.append(f"- {r['rule'].strip()}")
    return "\n".join(lines)


# Failure text -> the rule ids that name the fix. Patterns are matched against the raw checker /
# simulator / compiler output. Keep this table small and verified; retrieve() covers the long tail.
ERROR_RULES = [
    (r"neuronxcc", ["mig-neuronxcc-namespace-forbidden"]),
    (r"has no attribute '(load|store)'", ["nl-load-store-are-experimental-wrappers"]),
    (r"has no attribute '(par_dim|mgrid|arange|mask)'", ["mig-mask-mgrid-arange-removed"]),
    (r"must be in \['psum'\]|dst must be in", ["mm-operands-sbuf-dst-psum"]),
    (r"must be in \['sbuf'\]|moving must be|stationary must be", ["mm-operands-sbuf-dst-psum"]),
    (r"contraction dimension \d+ exceeds pmax", ["mm-contraction-on-partition-dim", "psum-accumulate-over-k"]),
    (r"partition dimension \d+ exceeds", ["layout-partition-dim-first-no-block-dims", "use-full-128-partitions"]),
    (r"moving free|gemm_moving_fmax|free dimension \d+ exceeds 512", ["mm-moving-free-le-512"]),
    (r"stationary free|gemm_stationary_fmax", ["mm-stationary-free-le-128"]),
    (r"uninitiali[sz]ed|NON-FINITE|NaN", ["mm-accumulate-first-write-must-overwrite", "psum-accumulate-flag-no-memset"]),
    (r"dma_copy.*psum|read.*PSUM.*dma", ["dma-copy-cannot-read-psum"]),
    (r"shared_hbm|OUTPUT IS .* ZEROS", ["output-tensors-shared-hbm"]),
    (r"transfers for .* output elements|bytes each", ["dma-free-dim-at-least-2kib-contiguous", "dma-descriptor-at-least-4kib", "row-loads-fewer-larger-transfers"]),
    (r"MEMORY BOUND|more reuse needed", ["load-once-reuse-in-sbuf", "block-m-n-to-cut-input-reloads", "hoist-parameter-loads-out-of-inner-loops"]),
    (r"SMALL DMA|bytes per partition", ["dma-free-dim-at-least-2kib-contiguous", "dma-descriptor-at-least-4kib"]),
]


def for_error(error_text, k=3):
    """Rules that name the fix for a failure. Table hits first, then retrieval on the error text."""
    byid = {r["id"]: r for r in rules()}
    out, seen = [], set()
    for pat, ids in ERROR_RULES:
        if re.search(pat, error_text or "", re.I):
            for i in ids:
                if i in byid and i not in seen:
                    out.append(byid[i]); seen.add(i)
    if len(out) < k:
        for r in retrieve(error_text, k=k * 2, detectable="static"):
            if r["id"] not in seen:
                out.append(r); seen.add(r["id"])
            if len(out) >= k:
                break
    return out[:k]


def instructions_for_error(error_text, k=2):
    rs = for_error(error_text, k)
    return " ".join(as_instruction(r) for r in rs)


if __name__ == "__main__":
    import sys
    q = " ".join(sys.argv[1:]) or "psum accumulate across K tiles"
    print(card()); print()
    for r in retrieve(q, k=5):
        print(f"[{r['score']}] {r['id']}: {r['rule']}")
        print("    fix:", (r.get('fix') or '')[:160])
