"""Turn runs/*.jsonl into the hand-in tables: solve rates with spread, held-out results, whether the
agent's claims were right, the failure taxonomy and where the tokens went. Writes runs/summary.md.

    python report.py                 # every real run
    python report.py --offline       # include offline smoke runs (never report these)
"""
import argparse
import collections
import glob
import json
import os
import statistics

HERE = os.path.dirname(os.path.abspath(__file__))


def load(include_offline):
    rows = []
    for path in sorted(glob.glob(os.path.join(HERE, "runs", "*.jsonl"))):
        if path.endswith("-offline.jsonl") and not include_offline:
            continue
        for line in open(path):
            if line.strip():
                rows.append(json.loads(line))
    return rows


MODES = [  # (tag, layer, what it means, what addressed it)
    ("EXCEPTION: dict unpacked as a tuple", "L1 runs",
     "`a, b, ... = state` assigns the dict's KEYS (strings); the crash surfaces lines later",
     "C3: the message names the unpacking line"),
    ("EXCEPTION: other", "L1 runs", "NameError, TypeError and friends, reported with line, step and state",
     "located message from C onward"),
    ("TRUNCATED / NO_CODE", "before L0", "the answer hit the token cap or had no code block",
     "tagged separately so a budget problem never reads as a model failure"),
    ("SYNTAX / NO_QUOTE_FN / FORBIDDEN_*", "L0 static", "does not parse, no quote(state), or a "
     "forbidden import or call", "static gate, never run"),
    ("CROSSED / TAKES / OFF_TICK / BAD_SIZE / FORMAT", "L2 rules", "an illegal quote on some step",
     "located fix per rule; 1-tick variants caught by L5 (C4) and the state probes"),
    ("INVENTORY_LIMIT", "L2 rules", "a quote that could push |inventory| past 10", "located fix; "
     "latent cases caught by the state probes"),
    ("OBLIGATION", "L3", "both sides near the touch on fewer than half the steps", "located message"),
    ("NO_FILLS (zero fills)", "L4 profit", "legal and present but never trades, so profit is exactly 0",
     "C2: the message says why nothing fills"),
    ("LOSS_INVENTORY", "L4 profit", "loses holding inventory into a trend", "located diagnosis (level 2)"),
    ("LOSS_ADVERSE", "L4 profit", "sells into heavy bids and buys into heavy asks (level 3)",
     "located diagnosis; C5 fill table (no effect); C6 published ideas (profit, not robustness)"),
    ("LOSS (other)", "L4 profit", "loses with no single dominant mechanism", "-"),
    ("SPREAD1", "L5 (C4+)", "passes at 2 ticks, fails the same markets at a 1-tick spread",
     "C7: the layer diagnoses its own failure"),
]


def mode_of(t):
    import checker
    tag = (t["tags"] or ["?"])[0]
    if tag == "EXCEPTION":
        return ("EXCEPTION: dict unpacked as a tuple" if t.get("code") and checker.unpacks_state(t["code"])
                else "EXCEPTION: other")
    if tag in ("TRUNCATED", "NO_CODE", "ENDPOINT_ERROR"):
        return "TRUNCATED / NO_CODE"
    if tag in ("SYNTAX", "NO_QUOTE_FN", "FORBIDDEN_IMPORT", "FORBIDDEN_CALL"):
        return "SYNTAX / NO_QUOTE_FN / FORBIDDEN_*"
    if tag in ("CROSSED", "TAKES", "OFF_TICK", "BAD_SIZE", "FORMAT"):
        return "CROSSED / TAKES / OFF_TICK / BAD_SIZE / FORMAT"
    if tag == "NO_FILLS" or (tag == "LOSS" and (t.get("metrics") or {}).get("fills", 1) < 5):
        return "NO_FILLS (zero fills)"
    if tag == "LOSS":
        return "LOSS (other)"
    return tag


def taxonomy(rows):
    tries = [r for r in rows if not r.get("final") and not r["solved"]]
    runs = sorted({t["run"] for t in tries}, key=lambda r: (len(r) > 1, r))
    c = collections.Counter((mode_of(t), t["run"]) for t in tries)
    tot = collections.Counter(t["run"] for t in tries)
    out = ["# Failure taxonomy\n",
           "Every unsolved attempt in `runs/*.jsonl` (dev probes excluded), classified by the first "
           "tag the checker gave it. Generated by `python report.py --taxonomy`. Exceptions are split by "
           "whether the code unpacks `state` as a tuple (the most common single bug).\n",
           "## The modes\n", "| mode | layer | what it means | what addressed it |", "|---|---|---|---|"]
    out += [f"| {m} | {layer} | {what} | {fix} |" for m, layer, what, fix in MODES]
    out += ["\n## Counts per arm (share of that arm's failed attempts)\n",
            "| mode | " + " | ".join(runs) + " |", "|---|" + "---|" * len(runs)]
    for m, *_ in MODES:
        if any(c[(m, r)] for r in runs):
            out.append(f"| {m} | " + " | ".join(
                f"{c[(m, r)]} ({c[(m, r)] / tot[r]:.0%})" if c[(m, r)] else "·" for r in runs) + " |")
    out.append("| **failed attempts** | " + " | ".join(str(tot[r]) for r in runs) + " |")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", action="store_true")
    ap.add_argument("--taxonomy", action="store_true", help="write TAXONOMY.md and stop")
    ap.add_argument("--deep", action="store_true",
                    help="also re-score verified strategies at spread 1 and on the real days")
    a = ap.parse_args()
    rows = load(a.offline)
    if a.taxonomy:
        text = taxonomy([r for r in rows])
        open(os.path.join(HERE, "TAXONOMY.md"), "w").write(text)
        print(text)
        return
    finals = [r for r in rows if r.get("final")]
    tries = [r for r in rows if not r.get("final")]
    out = []
    p = out.append
    p("# Market-maker agent: results\n")
    p("Generated by `report.py` from `runs/*.jsonl`. Dev = 16 seeded episodes per check; held-out = "
      "32 frozen seeds the agent never saw (`eval/heldout_seeds.txt`).\n")

    if a.deep:
        import hostile
        import lobster
        CHANGE = {"A": "score only", "B": "raw metrics (JSON)", "C": "located diagnosis",
                  "C2": "C + no-fills rule", "C3": "C2 + exception names its cause",
                  "C4": "C3 + spread-1 layer in the checker", "C4b": "C4, 2 extra level-3 repeats",
                  "C5": "C4 + fill table (level 3 only)",
                  "C6": "C5 + published ideas in the prompt (level 3 only)",
                  "C6r": "C6 settings on levels 1-2 (regression check)",
                  "C7": "C6 + the 1-tick layer diagnoses its failure (level 3 only)",
                  "C7r": "C7 settings on levels 1-2 (regression check)"}
        p("## Arms at a glance\n")
        p("Verified = the agent's own claim on the dev seeds. Held-out, spread 1 and the real days "
          "re-score only the verified strategies. Real day = legal (no rule violation) on both "
          "MSFT and INTC, and profitable (positive lower bound) on either.\n")
        p("| arm | change | level-runs verified | distinct strategies | held-out | spread 1 "
          "(hostile) | real day: legal | real day: profitable | tokens per level-run |")
        p("|---|---|---|---|---|---|---|---|---|")
        by = collections.defaultdict(list)
        for f in finals:
            by[f["run"]].append(f)
        for run in sorted(by):
            fs = by[run]
            ver = [f for f in fs if f["dev_solved"]]
            codes = {}
            for f in ver:
                codes.setdefault(f["code"], f["level"])
            h1 = legal = prof = 0
            for code, lv in codes.items():
                h1 += hostile.check_spread1(code, lv)[0] == "PASS"
                rs = [lobster.score(code, t) for t in lobster.TICKERS]
                legal += all(not r.get("error") and not r["violations"] for r in rs)
                prof += any(not r.get("error") and r["lcb"] > 0 for r in rs)
            p(f"| {run} | {CHANGE.get(run, '')} | {len(ver)}/{len(fs)} | {len(codes)} | "
              f"{sum(f['heldout_solved'] for f in ver)}/{len(ver)} | {h1}/{len(codes)} | "
              f"{legal}/{len(codes)} | {prof}/{len(codes)} | "
              f"{statistics.mean(f['tokens'] for f in fs):.0f} |")
        p("")

    p("## Solve rates\n")
    p("| run | feedback | level | reps | solved on dev | passed held-out | attempts to solve "
      "(each rep) | tokens per level (mean) |")
    p("|---|---|---|---|---|---|---|---|")
    groups = collections.defaultdict(list)
    for f in finals:
        groups[(f["run"], f["feedback_mode"], f["level"])].append(f)
    for (run, mode, lv), fs in sorted(groups.items()):
        ats = [f["attempts_to_solve"] if f["attempts_to_solve"] else "-" for f in fs]
        p(f"| {run} | {mode} | {lv} | {len(fs)} | {sum(f['dev_solved'] for f in fs)}/{len(fs)} | "
          f"{sum(f['heldout_solved'] for f in fs)}/{len(fs)} | {ats} | "
          f"{statistics.mean(f['tokens'] for f in fs):.0f} |")

    p("\n## Were the agent's claims right?\n")
    p("The agent claims `VERIFIED on dev` only when its strategy passed the profit bar on the dev "
      "seeds. Each claim is then graded on the held-out seeds.\n")
    p("| run | verified and held | verified but failed held-out (false claim) | "
      "not verified, failed held-out (honest) | not verified but held (under-claim) | "
      "distinct verified strategies |")
    p("|---|---|---|---|---|---|")
    by_run = collections.defaultdict(list)
    for f in finals:
        by_run[f["run"]].append(f)
    for run, fs in sorted(by_run.items()):
        c = collections.Counter((f["dev_solved"], f["heldout_solved"]) for f in fs)
        distinct = len({f["code"] for f in fs if f["dev_solved"] and f.get("code")})
        p(f"| {run} | {c[(True, True)]} | {c[(True, False)]} | {c[(False, False)]} | "
          f"{c[(False, True)]} | {distinct} |")

    p("\n## Failure taxonomy (every unsolved attempt, by its first tag)\n")
    p("| run | tag | count | share |")
    p("|---|---|---|---|")
    for run in sorted({t["run"] for t in tries}):
        ts = [t for t in tries if t["run"] == run and not t["solved"]]
        def label(t):
            tag = (t["tags"] or ["?"])[0]
            # post-hoc split of the frozen runs' catch-all LOSS: strategies that never traded
            if tag == "LOSS" and (t.get("metrics") or {}).get("fills", 1) < 5:
                return "LOSS (zero fills, post-hoc label)"
            return tag
        c = collections.Counter(label(t) for t in ts)
        for tag, n in c.most_common():
            p(f"| {run} | {tag} | {n} | {n / max(1, len(ts)):.0%} |")

    p("\n## Where the tokens went (mean per attempt)\n")
    p("| run | attempts | prompt chars: spec / code / feedback / ledger | prompt tokens | "
      "completion tokens | seconds | truncated | no code |")
    p("|---|---|---|---|---|---|---|---|")
    for run in sorted({t["run"] for t in tries}):
        ts = [t for t in tries if t["run"] == run]
        m = lambda k: statistics.mean(t["chars"][k] for t in ts)  # noqa: E731
        pt = [t["prompt_tokens"] for t in ts if t.get("prompt_tokens")]
        ct = [t["completion_tokens"] for t in ts if t.get("completion_tokens")]
        p(f"| {run} | {len(ts)} | {m('spec'):.0f} / {m('code'):.0f} / {m('feedback'):.0f} / "
          f"{m('ledger'):.0f} | {statistics.mean(pt) if pt else float('nan'):.0f} | "
          f"{statistics.mean(ct) if ct else float('nan'):.0f} | "
          f"{statistics.mean(t['seconds'] for t in ts):.0f} | "
          f"{sum(t['finish_reason'] == 'length' for t in ts)} | "
          f"{sum(t['stage'] == 'no_code' for t in ts)} |")

    p("\n## Device measurements (Trainium2, seat 94)\n")
    p("Every model generation ran on the chip: Qwen3-8B, vLLM-Neuron, tensor parallel 2, context "
      "8192, thinking off, up to 4 requests in flight. Every grade ran on the CPU in the seeded "
      "simulator (0.2–0.7 s per 16–32 episodes, from `calibrate.py`). No number here is a "
      "device-performance claim beyond these.\n")
    p("| run | attempts | median completion tokens | median tokens/s per request | median s per attempt "
      "| device time (attempt-hours) |")
    p("|---|---|---|---|---|---|")
    for run in sorted({t["run"] for t in tries}) + ["all"]:
        ts = [t for t in tries if run == "all" or t["run"] == run]
        ct = [t["completion_tokens"] for t in ts if t.get("completion_tokens")]
        tps = [t["completion_tokens"] / t["seconds"] for t in ts
               if t.get("completion_tokens") and t.get("seconds")]
        sec = [t["seconds"] for t in ts if t.get("seconds")]
        p(f"| {run} | {len(ts)} | {statistics.median(ct) if ct else float('nan'):.0f} | "
          f"{statistics.median(tps) if tps else float('nan'):.1f} | "
          f"{statistics.median(sec) if sec else float('nan'):.0f} | {sum(sec) / 3600:.1f} |")

    p("\n## Confidence calibration\n")
    p("Confidence = the chance the chosen strategy is verified: 0 if it stopped at any layer before "
      "profit (rules, obligation, the 1-tick layer), otherwise the chance it is profitable from its "
      "dev mean and standard error. Recomputed here from the logged dev metrics for every run. "
      "Run C7's own log field measures profit only, which ignores the 1-tick layer. Graded against "
      "the held-out result.\n")
    import math
    best_try = {}
    for t in tries:
        k = (t["run"], t["rep"], t["level"])
        if k not in best_try or t["score"] > best_try[k]["score"]:
            best_try[k] = t
    conf, outcome = [], []
    for f in finals:
        b = best_try.get((f["run"], f["rep"], f["level"])) or {}
        m = b.get("metrics") or {}
        c = (0.5 * (1 + math.erf(m["pnl_mean"] / m["pnl_se"] / math.sqrt(2)))
             if b.get("stage") in ("profit", "solved") and m.get("pnl_se") else 0.0)
        conf.append(c)
        outcome.append(1.0 if f["heldout_solved"] else 0.0)
    if conf:
        brier = statistics.mean((c - o) ** 2 for c, o in zip(conf, outcome))
        hi = [o for c, o in zip(conf, outcome) if c >= 0.975]
        lo = [o for c, o in zip(conf, outcome) if c < 0.975]
        p(f"{len(conf)} claims. Brier score {brier:.3f} (0 is perfect, 0.25 is a coin flip). "
          f"Confidence ≥ 97.5%: {len(hi)} claims, {sum(hi):.0f} held out. Below: {len(lo)} claims, "
          f"{sum(lo):.0f} held out.\n")

    text = "\n".join(out) + "\n"
    os.makedirs(os.path.join(HERE, "runs"), exist_ok=True)
    open(os.path.join(HERE, "runs", "summary.md"), "w").write(text)
    print(text)


if __name__ == "__main__":
    main()
