"""Summarise agent runs: solve rates, attempts, tokens, and the failure taxonomy, per arm and level.

    uv run python scripts/analyze.py ours=runs/bench-L123-r5.jsonl naive=runs/naive-L123-r5.jsonl \
        --tex notes/generated/results.tex

Prints plain-text tables and, with --tex, writes LaTeX tables the notes \\input. Every number is a
rate over runs, never a best run.
"""
import argparse
import json
import statistics
from collections import Counter, defaultdict
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

FAMILY_ORDER = ["reply", "syntax", "no-kernel", "load-crash", "crash", "timeout", "shape", "rule",
                "numeric"]


def load(path):
    rows = [json.loads(x) for x in Path(path).read_text().splitlines() if x.strip()]
    return [r for r in rows if r["type"] == "attempt"], [r for r in rows if r["type"] == "result"]


def family(key):
    return key.split(":")[0] if key else "?"


def fmt(x, nd=1):
    return "--" if x is None else f"{x:.{nd}f}"


def summarise(arms):
    """arms: {label: (attempts, results)} -> per (label, level) dict."""
    table = {}
    for label, (atts, res) in arms.items():
        for lv in sorted({r["level"] for r in res}):
            rs = [r for r in res if r["level"] == lv]
            ok = [r for r in rs if r["status"] == "verified"]
            st = Counter(r["status"] for r in rs)
            la = [a for a in atts if a["level"] == lv]
            table[label, lv] = dict(
                runs=len(rs), verified=len(ok), status=st,
                att_ok=statistics.mean(r["attempts"] for r in ok) if ok else None,
                att_all=statistics.mean(r["attempts"] for r in rs),
                tin=statistics.mean(r["tokens_in"] for r in rs),
                tout=statistics.mean(r["tokens_out"] for r in rs),
                peak_prompt=max((a["prompt_tokens"] for a in la), default=0),
                keys=Counter(a["key"] for a in la if a.get("key")),
            )
    return table


def recheck_dev_only(arms, timeout_s=600.0):
    """A 'dev-only' verdict means the kernel failed holdout. Holdout shapes are larger, so a correct
    but very slow kernel (per-element triple loops) can fail by the 20 s per-case timeout alone.
    Re-run holdout with a long timeout to tell 'slow' from 'wrong'; the benchmark itself is unchanged."""
    from kagent import harness
    from kagent.levels import LEVELS
    old = harness.CASE_TIMEOUT_S
    harness.CASE_TIMEOUT_S = timeout_s
    try:
        for label, (_, res) in arms.items():
            for r in res:
                if r["status"] == "dev-only" and r.get("code"):
                    h = harness.verify(LEVELS[r["level"]], r["code"], holdout=True)
                    r["recheck"] = "slow-but-correct" if h.passed else "wrong-on-holdout"
                    print(f"recheck {label} L{r['level']} run{r['run']}: {r['recheck']} ({h.summary()})")
    finally:
        harness.CASE_TIMEOUT_S = old


def efficiency(arms):
    """Roofline metrics of every verified kernel, re-measured from its code (dev, largest case)."""
    from kagent.levels import LEVELS
    from roofline import measure
    rows = []
    for label, (_, res) in arms.items():
        for r in res:
            if r["status"] == "verified" and r.get("code"):
                m = measure(LEVELS[r["level"]], r["code"])
                rows.append(dict(arm=label, level=r["level"], run=r["run"], **m))
    return rows


def print_efficiency(rows):
    if not rows:
        return
    print("\nefficiency of verified kernels (roofline time vs minimum; 1.00 = at the roofline)")
    print(f"{'arm':8s} {'L':>2s} {'run':>3s} {'time':>6s} {'reads':>6s} {'flops':>6s} {'FLOP/B':>7s} "
          f"{'bound':>7s} {'ops':>7s} {'elem/op':>8s}")
    for r in sorted(rows, key=lambda r: (r["level"], r["arm"], r["run"])):
        print(f"{r['arm']:8s} {r['level']:>2d} {r['run']:>3d} {r['time_x']:>5.2f}x {r['reads_x']:>5.2f}x "
              f"{(r['flops_x'] or 0):>5.2f}x {r['intensity']:>7.2f} {r['bound']:>7s} {r['ops']:>7d} "
              f"{r['elems_per_op']:>8.0f}")


def write_efficiency_tex(rows, path):
    by = defaultdict(list)
    for r in rows:
        by[r["arm"], r["level"]].append(r)
    lines = ["% generated by scripts/analyze.py; efficiency of verified kernels (mean over runs)",
             r"\begin{tabular}{@{}llrrrrrr@{}}", r"\toprule",
             r"Level & Arm & Kernels & Roofline time & HBM reads & FLOPs & FLOP/byte & Elements/instr. \\",
             r"\midrule"]
    for (arm, lv), rs in sorted(by.items(), key=lambda kv: (kv[0][1], kv[0][0])):
        mean = lambda k: statistics.mean(r[k] or 0 for r in rs)
        lines.append(f"L{lv} & {tex_escape(arm)} & {len(rs)} & {mean('time_x'):.2f}$\\times$ & "
                     f"{mean('reads_x'):.2f}$\\times$ & {mean('flops_x'):.2f}$\\times$ & "
                     f"{mean('intensity'):.2f} & {mean('elems_per_op'):.0f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("\n".join(lines) + "\n")
    print(f"wrote {path}")


def print_tables(table):
    print(f"{'arm':8s} {'L':>2s} {'verified':>9s} {'att|ok':>7s} {'att|all':>8s} {'in tok':>8s} "
          f"{'out tok':>8s} {'peak in':>8s}  statuses")
    for (label, lv), t in sorted(table.items(), key=lambda kv: (kv[0][1], kv[0][0])):
        print(f"{label:8s} {lv:>2d} {t['verified']:>4d}/{t['runs']:<4d} {fmt(t['att_ok']):>7s} "
              f"{fmt(t['att_all']):>8s} {t['tin']:>8.0f} {t['tout']:>8.0f} {t['peak_prompt']:>8d}  "
              f"{dict(t['status'])}")
    print("\nfailure taxonomy (failed attempts, by class)")
    for (label, lv), t in sorted(table.items(), key=lambda kv: (kv[0][1], kv[0][0])):
        if t["keys"]:
            print(f"  {label:8s} L{lv}: " + ", ".join(f"{k} x{n}" for k, n in t["keys"].most_common()))


def tex_escape(s):
    return s.replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


def write_tex(table, path, sources):
    arms = sorted({a for a, _ in table})
    lines = [f"% generated by scripts/analyze.py from {', '.join(sources)}; do not edit by hand",
             r"\begin{tabular}{@{}llrrrrr@{}}", r"\toprule",
             r"Level & Arm & Verified & Attempts (verified) & Attempts (all) & Tokens in & Tokens out \\",
             r"\midrule"]
    levels = sorted({lv for _, lv in table})
    for lv in levels:
        for arm in arms:
            t = table.get((arm, lv))
            if not t:
                continue
            lines.append(f"L{lv} & {tex_escape(arm)} & {t['verified']}/{t['runs']} & {fmt(t['att_ok'])} & "
                         f"{fmt(t['att_all'])} & {t['tin']:.0f} & {t['tout']:.0f} \\\\")
        if lv != levels[-1]:
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}", "", r"\medskip", ""]

    fams = Counter()
    for t in table.values():
        for k, n in t["keys"].items():
            fams[k] += n
    lines += [r"\begin{tabular}{@{}l" + "r" * len(arms) + "@{}}", r"\toprule",
              "Failure class & " + " & ".join(tex_escape(a) for a in arms) + r" \\", r"\midrule"]
    for k in sorted(fams, key=lambda k: (FAMILY_ORDER.index(family(k)) if family(k) in FAMILY_ORDER else 99, k)):
        counts = [sum(t["keys"].get(k, 0) for (a, _), t in table.items() if a == arm) for arm in arms]
        lines.append(f"\\code{{{tex_escape(k)}}} & " + " & ".join(map(str, counts)) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("\n".join(lines) + "\n")
    print(f"\nwrote {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("arms", nargs="+", help="label=path.jsonl")
    ap.add_argument("--tex")
    ap.add_argument("--eff-tex", help="also write the efficiency table here")
    ap.add_argument("--recheck", action="store_true",
                    help="re-run holdout of dev-only kernels with a long timeout (slow vs wrong)")
    a = ap.parse_args()
    arms = {}
    for spec in a.arms:
        label, path = spec.split("=", 1)
        arms[label] = load(path)
    for label, (_, res) in arms.items():
        versions = sorted({r.get("version", "?") for r in res})
        print(f"{label}: code version(s) {versions}" + ("  <-- MIXED" if len(versions) > 1 else ""))
    if a.recheck:
        recheck_dev_only(arms)
    table = summarise(arms)
    print_tables(table)
    if a.tex:
        write_tex(table, a.tex, [s.split("=", 1)[1] for s in a.arms])
    rows = efficiency(arms)
    print_efficiency(rows)
    if a.eff_tex and rows:
        write_efficiency_tex(rows, a.eff_tex)


if __name__ == "__main__":
    main()
