"""Write the eval set as a readable listing (a deliverable): every dev and holdout case per level,
its shape, value kind and tags, plus the error bound and the level-specific diagnosis.

    uv run python scripts/list_cases.py            # writes EVALSET.md and notes/generated/evalset.tex
"""
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import numpy as np  # noqa: E402

from kagent.levels import LEVELS  # noqa: E402

BOUND = {1: "gamma_3 * (|a||x| + |b|)", 2: "gamma_N * sum|x|", 3: "exact (k = 0)",
         4: "gamma_(N+4) * |y|", 5: "gamma_(N+4) * y (1 + |x - max|) + 2^-126",
         6: "exact (k = 0)", 7: "gamma_(K+1) * |A||B|",
         8: "gamma_(N+6) * |g| (|y_hat| + mean|x| / sigma) + |b|",
         9: "gamma_(d+W+8) * (p|v|)(1 + max|q||k|/sqrt d) + 2^-126", 10: "gamma_(C_in K + 1) * |w| * |x|"}
DIAG = {2: "per-column-tile overwrite", 3: "per-column-tile overwrite", 4: "per-tile statistic",
        5: "per-tile statistic", 6: "decode each wrong output to its source index",
        7: "missing partial K tile", 8: "cancellation (mean/std >= 30); per-tile statistic",
        9: "window w +- 1; one-sided window", 10: "ignored dilation"}


def shape_of(case):
    arrs = [a for a in case.args if isinstance(a, np.ndarray)]
    return " , ".join("x".join(map(str, a.shape)) for a in arrs)


def scalars_of(case):
    return ", ".join(f"{a:g}" if isinstance(a, float) else str(a)
                     for a in case.args if not isinstance(a, np.ndarray))


def main():
    md = ["# Eval set", "",
          "Generated by `scripts/list_cases.py` from `kagent/levels.py`. Inputs are float32; the",
          "reference is float64 on the same values. A case passes when every output element is within",
          "the proven float32 bound `gamma_k * scale` (`gamma_k = k u / (1 - k u)`, `u = 2^-24`).",
          "Dev cases are shown to the model through feedback; holdout cases (other shapes and seeds)",
          "never are, and decide the confidence of a kernel that passed dev.", ""]
    tex = ["% generated by scripts/list_cases.py", r"\begin{tabular}{@{}rlrrl@{}}", r"\toprule",
           r"Level & Op & Dev & Holdout & Value kinds (dev) \\", r"\midrule"]
    total = [0, 0]
    for n, lv in LEVELS.items():
        dev, hold = lv.get_cases(), lv.get_cases(True)
        total[0] += len(dev)
        total[1] += len(hold)
        kinds = Counter(c.name.split()[0] for c in dev)
        tags = Counter(t for c in dev for t in c.tags if t not in kinds)
        md += [f"## L{n} {lv.name}: `{lv.signature}`", "", lv.task, "",
               f"- bound: `{BOUND[n]}`", f"- level-specific diagnosis: {DIAG.get(n, '-')}",
               f"- dev: {len(dev)} cases; holdout: {len(hold)} cases",
               f"- value kinds: " + ", ".join(f"{k} x{v}" for k, v in kinds.items()),
               f"- shape tags: " + ", ".join(f"{k} x{v}" for k, v in sorted(tags.items())), "",
               "| set | case | shapes | scalars |", "|---|---|---|---|"]
        for label, cs in (("dev", dev), ("holdout", hold)):
            md += [f"| {label} | {c.name} | {shape_of(c)} | {scalars_of(c)} |" for c in cs]
        md.append("")
        tex.append(f"L{n} & \\code{{{lv.name.replace('_', chr(92) + '_')}}} & {len(dev)} & {len(hold)} & "
                   + ", ".join(k for k in kinds) + r" \\")
    tex += [r"\midrule", f"& total & {total[0]} & {total[1]} & \\\\", r"\bottomrule", r"\end{tabular}"]
    md.insert(7, f"**Total: {total[0]} dev cases and {total[1]} holdout cases over {len(LEVELS)} levels.**\n")
    (ROOT / "EVALSET.md").write_text("\n".join(md) + "\n")
    out = ROOT / "notes/generated/evalset.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(tex) + "\n")
    print(f"wrote EVALSET.md and {out.relative_to(ROOT)}: {total[0]} dev, {total[1]} holdout")


if __name__ == "__main__":
    main()
