"""Summarise optimiser runs: roofline time before and after, per kernel, plus what each round did.

    uv run python scripts/opt_report.py runs/opt-live.jsonl --tex notes/generated/opt.tex

Writes <log>.png: roofline time before vs after per kernel (1.00 = at the roofline).
"""
import argparse
import json
from collections import Counter
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

# reference categorical palette slots 1-2 (validated with slots 3-4 for the token plot)
BEFORE, AFTER = "#2a78d6", "#eb6834"
INK, MUTED, SURFACE, GRID = "#0b0b0b", "#52514e", "#fcfcfb", "#e6e4df"


def summarise(steps):
    kernels = {}
    for s in steps:
        k = (s["level"], s["source"])
        d = kernels.setdefault(k, dict(level=s["level"], source=s["source"], start=s["before"],
                                       final=s["before"], rounds=0, outcomes=Counter()))
        d["rounds"] += 1
        d["outcomes"][s["outcome"]] += 1
        if s["outcome"] == "accepted":
            d["final"] = s["after"]
    return sorted(kernels.values(), key=lambda d: (d["level"], d["source"]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("log")
    ap.add_argument("--tex")
    a = ap.parse_args()
    steps = [json.loads(x) for x in Path(a.log).read_text().splitlines() if x.strip()]
    ks = summarise(steps)

    print(f"{'kernel':16s} {'time':>13s} {'reads':>13s} {'flops':>13s} {'ops':>15s}  rounds")
    for d in ks:
        b, f = d["start"], d["final"]
        print(f"L{d['level']} {d['source']:13s} {b['time_x']:5.2f}->{f['time_x']:5.2f}x "
              f"{b['reads_x']:5.2f}->{f['reads_x']:5.2f}x {(b['flops_x'] or 0):5.2f}->{(f['flops_x'] or 0):5.2f}x "
              f"{b['ops']:>6d}->{f['ops']:<6d}  {dict(d['outcomes'])}")
    total = Counter()
    for d in ks:
        total += d["outcomes"]
    print(f"\nall rounds: {dict(total)}")

    if a.tex:
        lines = ["% generated by scripts/opt_report.py", r"\begin{tabular}{@{}llrrrl@{}}", r"\toprule",
                 r"Level & Kernel & Roofline time & HBM reads & FLOPs & Rounds \\", r"\midrule"]
        for d in ks:
            b, f = d["start"], d["final"]
            oc = ", ".join(f"{k} {v}" for k, v in sorted(d["outcomes"].items()))
            lines.append(f"L{d['level']} & \\code{{{d['source'].replace('_', chr(92) + '_')}}} & "
                         f"{b['time_x']:.2f} $\\to$ {f['time_x']:.2f} & {b['reads_x']:.2f} $\\to$ {f['reads_x']:.2f} & "
                         f"{(b['flops_x'] or 0):.2f} $\\to$ {(f['flops_x'] or 0):.2f} & {oc} \\\\")
        lines += [r"\bottomrule", r"\end{tabular}"]
        Path(a.tex).parent.mkdir(parents=True, exist_ok=True)
        Path(a.tex).write_text("\n".join(lines) + "\n")
        print(f"wrote {a.tex}")

    labels = [f"L{d['level']} {d['source']}" for d in ks]
    x = list(range(len(ks)))
    w = 0.36
    # two panels, one measure each: roofline time (linear) and instructions (log); never a dual axis
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(max(6, 0.95 * len(ks) + 2), 6.4), sharex=True,
                                   facecolor=SURFACE)
    for ax, key, title, log in ((ax1, "time_x", "Roofline time / minimum (1.00 = at the roofline)", False),
                                (ax2, "ops", "Instructions issued (log scale)", True)):
        ax.set_facecolor(SURFACE)
        before = [d["start"][key] for d in ks]
        after = [d["final"][key] for d in ks]
        ax.bar([i - w / 2 for i in x], before, w, color=BEFORE, label="before", edgecolor=SURFACE, linewidth=1.5)
        ax.bar([i + w / 2 for i in x], after, w, color=AFTER, label="after optimisation", edgecolor=SURFACE, linewidth=1.5)
        for i, (b, f) in enumerate(zip(before, after)):
            if f < b * 0.95:
                lab = f"{b / f:.0f}x fewer" if log else f"-{(1 - f / b):.0%}"
                ax.text(i + w / 2, f, lab, ha="center", va="bottom", fontsize=7.5, color=INK)
        if log:
            ax.set_yscale("log")
        else:
            ax.axhline(1.0, color=MUTED, linewidth=1, linestyle=(0, (4, 3)))
            ax.set_ylim(0, max(before + after) * 1.2)
        ax.set_title(title, loc="left", fontsize=10, color=INK)
        ax.grid(axis="y", color=GRID, linewidth=0.8)
        ax.set_axisbelow(True)
        for side in ("top", "right", "left"):
            ax.spines[side].set_visible(False)
        ax.spines["bottom"].set_color("#d0cec8")
        ax.tick_params(axis="y", labelsize=8, colors=MUTED)
    ax1.legend(frameon=False, fontsize=8, loc="upper left")
    ax2.set_xticks(x, labels, rotation=30, ha="right", fontsize=8, color=MUTED)
    fig.suptitle("Verified kernels before and after the efficiency stage", x=0.01, ha="left",
                 fontsize=11, color=INK)
    fig.tight_layout()
    out = Path(a.log).with_suffix(".png")
    fig.savefig(out, dpi=160, facecolor=SURFACE)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
