"""Failure taxonomy over every agent run: each failed attempt mapped to a named failure mode,
counted per level and arm, plus the class each unsolved run stopped on and how often a repair
fixed the error it was shown but broke something else (fewer cases passing than before).

    uv run python scripts/taxonomy.py ours=results/seat-130/ours-L1234-seat-130.jsonl ... \
        --tex notes/generated/taxonomy.tex --md TAXONOMY.md
"""
import argparse
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

MODES = [  # (mode, description, predicate on the failure key)
    ("banned reduction", "called np.sum / np.max / np.mean (or a builtin) instead of a column loop",
     lambda k: k in ("rule:sum-like", "rule:max-like", "rule:reduction", "rule:builtin-reduce")),
    ("hid the tiling", "whole-array op, np.asarray/escape, reshape/transpose/newaxis, broadcasting, fancy index",
     lambda k: k.startswith("rule:")),
    ("crash", "IndexError / ValueError / ... while running (mostly shapes at a partial tile)",
     lambda k: k.startswith("crash:") or k in ("timeout", "shape", "load-crash", "syntax", "no-kernel")),
    ("partial tile / bounds", "the last partial tile or the last row/col is wrong or missing",
     lambda k: k.startswith(("numeric:partial", "numeric:last", "numeric:tag:partial", "numeric:tag:multi",
                             "numeric:tag:dim-1", "numeric:band-edge", "numeric:tile-origin"))),
    ("accumulator across tiles", "result overwritten per tile, or a row statistic from one tile only",
     lambda k: k in ("numeric:tile-overwrite", "numeric:per-tile-stat")),
    ("floating point", "overflow / NaN, cancellation, wrong identity (0 for max), precision",
     lambda k: k in ("numeric:nonfinite", "numeric:precision", "numeric:identity", "numeric:cancellation")
     or k.startswith(("numeric:tag:huge", "numeric:tag:large", "numeric:tag:all-neg", "numeric:tag:huge-neg"))),
    ("unexplained wrong numbers", "wrong values the harness could not attribute",
     lambda k: k.startswith("numeric:")),
    ("no usable reply", "truncated, empty, or no code block",
     lambda k: k.startswith("reply:")),
]


def mode_of(key):
    return next((m for m, _, p in MODES if p(key)), "other")


def n_pass(summary):
    m = re.search(r"(\d+)/(\d+) cases correct", summary or "")
    return int(m.group(1)) if m else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("arms", nargs="+", help="label=path.jsonl (several files per label allowed: label=a,b)")
    ap.add_argument("--tex")
    ap.add_argument("--md")
    a = ap.parse_args()

    counts = defaultdict(Counter)        # (arm, level) -> mode -> attempts
    stops = defaultdict(Counter)         # (arm, level) -> mode the unsolved run stopped on
    regress = Counter()                  # (arm) -> repairs that lowered the passing count
    repairs = Counter()
    for spec in a.arms:
        label, paths = spec.split("=", 1)
        for path in paths.split(","):
            rows = [json.loads(x) for x in Path(path).read_text().splitlines() if x.strip()]
            last = {}
            for r in rows:
                if r["type"] == "attempt":
                    key = (r["level"], r["run"])
                    if r.get("key"):
                        counts[label, r["level"]][mode_of(r["key"])] += 1
                    p = n_pass(r.get("summary"))
                    if r["prompt_kind"] == "repair" and p is not None and key in last:
                        repairs[label] += 1
                        if p < last[key]:
                            regress[label] += 1
                    if p is not None:
                        last[key] = p
                elif r["type"] == "result" and r["status"] in ("failed", "stuck") and r.get("final_key"):
                    stops[label, r["level"]][mode_of(r["final_key"])] += 1

    arms = sorted({arm for arm, _ in counts})
    levels = sorted({lv for _, lv in counts})
    modes = [m for m, _, _ in MODES] + ["other"]
    print(f"{'mode':28s}" + "".join(f"{arm[:6]} L{lv:<3d}" for arm in arms for lv in levels if counts[arm, lv]))
    for m in modes:
        row = [counts[arm, lv][m] for arm in arms for lv in levels if counts[arm, lv]]
        if any(row):
            print(f"{m:28s}" + "".join(f"{v:>9d}" for v in row))
    print("\nunsolved runs stopped on:")
    for (arm, lv), c in sorted(stops.items()):
        print(f"  {arm} L{lv}: " + ", ".join(f"{m} x{n}" for m, n in c.most_common()))
    print("\nfixed what it was shown but broke something else (passing cases went down after a repair):")
    for arm in arms:
        print(f"  {arm}: {regress[arm]} of {repairs[arm]} repairs")

    cols = [(arm, lv) for arm in arms for lv in levels if counts[arm, lv]]
    if a.md:
        md = ["# Failure taxonomy", "", "Generated by `scripts/taxonomy.py`. Counts are failed attempts.", "",
              "| failure mode | what it means | " + " | ".join(f"{arm} L{lv}" for arm, lv in cols) + " |",
              "|---|---|" + "---|" * len(cols)]
        for m, desc, _ in MODES + [("other", "", None)]:
            row = [counts[c][m] for c in cols]
            if any(row):
                md.append(f"| {m} | {desc} | " + " | ".join(map(str, row)) + " |")
        md += ["", "Unsolved runs stopped on: " + "; ".join(
            f"{arm} L{lv}: " + ", ".join(f"{m} x{n}" for m, n in c.most_common()) for (arm, lv), c in sorted(stops.items())),
               "", "Repairs that fixed the error shown but lowered the number of passing cases: " +
               "; ".join(f"{arm} {regress[arm]}/{repairs[arm]}" for arm in arms), ""]
        Path(a.md).write_text("\n".join(md))
        print(f"wrote {a.md}")
    if a.tex:
        esc = lambda t: t.replace("_", r"\_").replace("&", r"\&")
        tex = ["% generated by scripts/taxonomy.py", r"\begin{tabular}{@{}l" + "r" * len(cols) + "@{}}", r"\toprule",
               "Failure mode & " + " & ".join(f"{esc(arm)} L{lv}" for arm, lv in cols) + r" \\", r"\midrule"]
        for m in modes:
            row = [counts[c][m] for c in cols]
            if any(row):
                tex.append(f"{m} & " + " & ".join(str(v) if v else "--" for v in row) + r" \\")
        tex += [r"\bottomrule", r"\end{tabular}"]
        Path(a.tex).parent.mkdir(parents=True, exist_ok=True)
        Path(a.tex).write_text("\n".join(tex) + "\n")
        print(f"wrote {a.tex}")


if __name__ == "__main__":
    main()
