#!/usr/bin/env python3
"""Collect every attempt into one readable log: ATTEMPT_LOG.md (+ attempt_log.csv).

Sources (all written automatically while the agent runs):
  attempts.jsonl                    every circuit the AI wrote or fixed (prompt step)
  designs/<name>/tb_attempts.jsonl  every testbench attempt: accepted / rejected + why
  designs/<name>/history.jsonl      every check of the design: score, pass/fail, judge verdict
  designs/<name>/report.json        the latest result (+ mutation score)
  scorecard_*.log                   the 9-circuit testbench exam runs

  python attempt_log.py            -> ATTEMPT_LOG.md and attempt_log.csv
"""
import os, re, csv, json, glob, time

def jl(path):
    out = []
    if os.path.exists(path):
        for line in open(path):
            try:
                out.append(json.loads(line))
            except Exception:
                pass
    return out

def ts(t):
    return time.strftime("%H:%M:%S", time.localtime(t)) if t else ""

def main(root="designs", out_md="ATTEMPT_LOG.md", out_csv="attempt_log.csv"):
    gen = jl("attempts.jsonl")
    by_folder = {}
    for a in gen:
        if a.get("folder"):
            by_folder.setdefault(os.path.normpath(a["folder"]), []).append(a)

    rows, md = [], ["# Attempt log", "",
                    "Every attempt the loop made, in order, per circuit. Score = fraction of testbench checks "
                    "passed (1.000 = PASS). Generated by `attempt_log.py`.", ""]

    # ---- the testbench exam ----
    cards = sorted(glob.glob("scorecard_*.log") + glob.glob("results/scorecard_*.log"))
    if cards:
        md += ["## Testbench exam runs (9 circuits, correct + buggy version each)", "",
               "| run | perfect | correct designs passed | bugs caught |", "|---|---|---|---|"]
        for c in cards:
            txt = open(c, errors="replace").read()
            m = re.search(r"perfect \(testbench built, correct passed, bug caught\): (\d+)/(\d+)", txt)
            if not m:
                continue
            block = txt[txt.rfind("TESTBENCH SCORECARD"):]
            ok = len(re.findall(r"PASS ✓", block))
            caught = len(re.findall(r"caught ✓", block))
            md.append(f"| {os.path.basename(c)[10:-4]} | {m[1]}/{m[2]} | {ok}/{m[2]} | {caught}/{m[2]} |")
        md.append("")

    # ---- per circuit ----
    folders = sorted(d for d in glob.glob(os.path.join(root, "*")) if os.path.isdir(d))
    totals = dict(circuits=0, passed=0, checks=0, tb=0, tb_ok=0)
    for d in folders:
        name = os.path.basename(d)
        events = []
        for a in by_folder.get(os.path.normpath(d), []):
            t = a.get("time", 0)
            t = t + 0.999 if isinstance(t, int) else t     # whole-second stamps are written AFTER the AI answers
            events.append((t, "prompt" if a.get("kind") == "design" else "fix",
                           f"AI {'wrote' if a.get('kind') == 'design' else 'fixed'} the circuit"
                           + (f" ({a.get('seconds')}s)" if a.get("seconds") else ""), ""))
        for i, t in enumerate(jl(os.path.join(d, "tb_attempts.jsonl"))):
            if t.get("kind") != "testbench":
                continue
            totals["tb"] += 1
            totals["tb_ok"] += bool(t.get("accepted"))
            why = "" if t.get("accepted") else (t.get("reason") or "")[:110]
            events.append((t.get("time", 0), "testbench",
                           f"{t.get('route', 'testbench')} attempt {t.get('attempt')}: "
                           f"{'accepted' if t.get('accepted') else 'rejected'}" + (f" - {why}" if why else ""), ""))
        hist = jl(os.path.join(d, "history.jsonl"))
        for h in hist:
            totals["checks"] += 1
            events.append((h.get("time", 0), "check",
                           f"{h.get('outcome')}: {h.get('first', '')}"
                           + (f" (judge: {h['judge']})" if h.get("judge") else ""), f"{h.get('score', 0):.3f}"))
        rep = json.load(open(os.path.join(d, "report.json"))) if os.path.exists(os.path.join(d, "report.json")) else {}
        if not events and not rep:
            continue
        totals["circuits"] += 1
        totals["passed"] += bool(rep.get("passed"))
        # events without timestamps (older logs) keep their file order
        events.sort(key=lambda e: e[0] or 0)
        spec = (open(os.path.join(d, "spec.txt")).read().strip().splitlines() or [""])[0] \
            if os.path.exists(os.path.join(d, "spec.txt")) else ""
        mut = rep.get("mutation")
        md += [f"## {name}", "", f"*Spec:* {spec[:160]}", "",
               "| # | time | step | what happened | score |", "|---|---|---|---|---|"]
        for i, (t, step, what, score) in enumerate(events, 1):
            md.append(f"| {i} | {ts(t)} | {step} | {what.replace('|', '/')} | {score} |")
            rows.append(dict(circuit=name, n=i, time=ts(t), step=step, what=what, score=score))
        scores = [f"{h.get('score', 0):.3f}" for h in hist]
        md += ["", f"**Result:** {'PASS' if rep.get('passed') else (hist[-1]['outcome'] if hist else 'FAIL')}"
               + (f" · scores {' → '.join(scores)}" if scores else "")
               + (f" · testbench caught {mut['killed']}/{mut['total']} planted bugs" if mut else ""), ""]

    md[3:3] = [f"**Totals:** {totals['circuits']} circuits · {totals['passed']} passing now · "
               f"{totals['checks']} checks · testbench attempts accepted {totals['tb_ok']}/{totals['tb']}", ""]
    open(out_md, "w").write("\n".join(md) + "\n")
    with open(out_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["circuit", "n", "time", "step", "what", "score"])
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {out_md} and {out_csv}: {totals['circuits']} circuits, {totals['checks']} checks, "
          f"{totals['tb']} testbench attempts")

if __name__ == "__main__":
    main()
